# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AKPageController' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


  pod 'YYCategories','1.0.4'
  pod 'ReactiveObjC','3.1.1'
  pod 'Masonry','1.1.0'
  pod 'SDWebImage','4.4.6'
  pod 'SDWebImage/GIF', '4.4.6'

  # Pods for AKPageController

  target 'AKPageControllerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AKPageControllerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
